[package]
name = "propolis-standalone-config"
version = "0.0.0"
license = "MPL-2.0"
edition = "2018"

[dependencies]
num_enum.workspace = true
serde.workspace = true
serde_derive.workspace = true
toml.workspace = true
