[package]
name = "propolis_types"
version = "0.0.0"
license = "MPL-2.0"
edition = "2021"

[lib]
test = false
doctest = false

[dependencies]
schemars = { workspace = true, features = [ "uuid1" ] }
serde.workspace = true

[dev-dependencies]
serde_test.workspace = true
