[package]
name = "bhyve_api"
version = "0.0.0"
license = "MPL-2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
bhyve_api_sys.workspace = true
libc.workspace = true
strum = { workspace = true, features = ["derive"] }
