name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Report rustfmt version
      run: cargo fmt -- --version
    - name: Check style
      run: cargo fmt -- --check
  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Report clippy version
      run: cargo clippy -- --version
    - name: Check clippy
      run: cargo xtask clippy --strict
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
    - name: Test build documentation
      run: cargo doc --workspace --no-deps
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
    - name: Build mock-only server
      run: cargo build --bin propolis-server --features mock-only
    - name: Build
      run: cargo build --verbose
    - name: Test Libraries
      run: cargo test --lib --verbose

